### ISSUE TITLE
Biosecurity Project - Allow configurable Alert emails

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/alerts#58]
**Background:** As part of the Biosecurity project, we will be using the ALA Alert functionality to notify DAWE of new potential pest records.  There is potential future expansion of this service to state based biosecurity groups. At the moment, the alert emails are designed for the general public.  It would be good if we could explore the potential to allow configurable (or templated) emails (eg: as per issue: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/405 for download emails), so that a more "professional" email is sent for biosecurity puposes while still maintaining the more "public-friendly" emails for the general public.

As a minimum, configurable changes should include:
- [ ] implementation of issue #60 for a more obvious reference to the ALA (at the moment the only indication the alert is from the Atlas is the @ala.org.au in the From address)
- [ ] implementation of issue #41 to more suitable "click here" text
- [ ] implementation of issue #42 to improve the "unsubscribe" text
- [ ] allow an option to exclude the display of individual records (with images) in the alert email

**Comment by nickdos** [comment]
#60, #41 & #42 are all small sized tasks.

The last task (option to customise the email output) is a medium-sized task (could be large even). What makes it harder is the  fact that we'll need to add logic to the email template (there is none ATM), we'll need to add a UI to allow the user to set the option (doesn't exist and not sure where we'd put it, as well as allow someone to change it for existing alerts).

It could be simplified by having a different email template for biosecurity alerts - that is custom for those users, e.g. just has a list with a link to the records in biocache.

The other thing that has not been specified, is how are we creating these alerts in the first place. The current alerts are generated from BIE, Collectory and Biocache pages but we don't currently have a page where you can create a custom alert. The Alerts system has an admin screen, where we could add this functionality - but its another task in the "medium" size range.

**Comment by m-hope** [comment]
Thanks Nick.  At this stage, there is no requirement for user configurable alert emails.  Your suggestion of just a different (pre-canned) template for biosecurity alerts would be satisfactory.  
The biosecurity alerts would be generated from Biocache, as we would be interested in any new records for species listed in a particular ALA List (eg: for this query: https://biocache.ala.org.au/occurrences/search?q=species_list_uid:dr16412)

**Comment by nickdos** [comment]
We'd still need some way of differentiating alerts for biosecurity versus general alerts for new records. Its still unclear how this would happen.

**Comment by Rita-C** [comment]
**Biocache** generates `alerts for new record` and `alerts for new annotation`. We could append a new param to the **Biocache** url to flag a biosecurity alert is required. **Alerts** then stores the value and selects a different template for sending email:
- [ ] update Biocache, add new param
- [ ] update Alerts, store new param value, select template based on the existence of the value
- [ ] create a new biosecurity template

**Comment by nickdos** [comment]
Moving back into To Do, as project objectives have been met for now.

**Comment by kylie-m** [comment]
closing as relates to old template
